workflows:
  ios-workflow:
    name: Chair Yoga iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.readwithlena.chairyoga
      vars:
        XCODE_SCHEME: "MoveWithLena"
      xcode: latest
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
